- build.gradle
- src/main/java/us/usserver/author/Author.java
- src/main/java/us/usserver/base/BaseEntity.java
- src/main/java/us/usserver/chapter/Chapter.java
- src/main/java/us/usserver/novel/Novel.java
- src/main/java/us/usserver/novel/novelEnum/AgeRating.java
- src/main/java/us/usserver/novel/novelEnum/Genre.java
- src/main/java/us/usserver/novel/novelEnum/Hashtag.java
- src/main/java/us/usserver/paragraph/Paragraph.java
- src/main/java/us/usserver/paragraph/paragraphEnum/ParagraphStatus.java
- src/main/java/us/usserver/score/Score.java
- src/main/java/us/usserver/score/scoreEnum/ScoreType.java
- src/main/java/us/usserver/stake/Stake.java
- 소설 (Novel)
- 회차 (Chapter)
- 한줄 (Paragraph)
- 평점 (Score)
- 후에 회차 평점, 소설 평점으로 나뉠 수 있을 것 같아서 enum으로 추가했습니다.
- 지분 (Stake)
1. Author 패키지를 만들기는 했는데, 그냥 관계만 보여주기 위해서 만든겁니다. 삭제하셔도 됩니다.
> 1차 엔티티 구현 사항입니다.

- src/main/java/us/usserver/author/Author.java
- src/main/java/us/usserver/authority/Authority.java
- src/main/java/us/usserver/chapter/Chapter.java
- src/main/java/us/usserver/comment/ChapterComment.java
- src/main/java/us/usserver/comment/NovelComment.java
- src/main/java/us/usserver/like/ChapterCommentLike.java
- src/main/java/us/usserver/like/NovelLike.java
- src/main/java/us/usserver/like/ParagraphLike.java
- src/main/java/us/usserver/novel/Novel.java
- src/main/java/us/usserver/paragraph/Paragraph.java
- src/main/java/us/usserver/score/Score.java
- src/main/java/us/usserver/stake/Stake.java
- src/main/java/us/usserver/user/User.java
- src/main/java/us/usserver/user/userEnum/Gender.java
- 유저(User)
- 접근권한(Authority)
- 좋아요(NovelLike, ParagraphLike, ChapterCommentLike)
- 댓글(NovelComment, ChapterComment)
- 각 Entity @Column id 값 추가
- Entity 개발로 인한 추가 연관관계 설정
> 2차 엔티티 구현 사항입니다.

- src/main/java/us/usserver/author/Author.java
- src/main/java/us/usserver/author/dto/AuthorInfo.java
- src/main/java/us/usserver/authority/AuthorService.java
- src/main/java/us/usserver/authority/AuthorityController.java
- src/main/java/us/usserver/authority/AuthorityService.java
- src/main/java/us/usserver/authority/service/AuthorServiceV0.java
- src/main/java/us/usserver/authority/service/AuthorityServiceV0.java
- src/main/java/us/usserver/bookshelf/Bookshelf.java
- src/main/java/us/usserver/bookshelf/BookshelfController.java
- src/main/java/us/usserver/bookshelf/BookshelfService.java
- src/main/java/us/usserver/bookshelf/dto/NovelPreview.java
- src/main/java/us/usserver/bookshelf/service/BookshelfServiceV0.java
- src/main/java/us/usserver/chapter/service/ChapterServiceV0.java
- src/main/java/us/usserver/like/novel/NovelLike.java
- src/main/java/us/usserver/like/novel/NovelLikeRepository.java
- src/main/java/us/usserver/novel/Novel.java
- src/main/java/us/usserver/novel/NovelController.java
- src/main/java/us/usserver/novel/service/NovelServiceV0.java
- src/main/java/us/usserver/stake/StakeController.java
- src/test/java/us/usserver/bookshelf/service/BookshelfServiceV0Test.java
- src/test/java/us/usserver/stake/service/StakeServiceV0Test.java
- 가장 최근에 merge한 main 브랜치 기준으로 테스트 및 빌드가 원활하게 동작하지 않아. 제대로 동작하는 것으로 다시 PR을 보냈습니다.
- 빌드 정상화 및 보관함 기능이 추가된 PR입니다!
> 보관함(Bookshelf)기능 구현 완료

- src/main/java/us/usserver/author/Author.java
- src/main/java/us/usserver/author/AuthorController.java
- src/main/java/us/usserver/author/AuthorService.java
- src/main/java/us/usserver/author/dto/UpdateAuthorReq.java
- src/main/java/us/usserver/author/service/AuthorServiceV0.java
- src/main/java/us/usserver/global/oauth/OauthAttributes.java
- src/main/java/us/usserver/global/oauth/OauthController.java
- src/main/java/us/usserver/member/MemberController.java
- src/main/java/us/usserver/member/MemberService.java
- src/main/java/us/usserver/member/service/MemberServiceV0.java
- src/main/java/us/usserver/novel/NovelController.java
- src/main/java/us/usserver/novel/NovelService.java
- src/main/java/us/usserver/novel/dto/SearchNovelReq.java
- src/main/java/us/usserver/novel/service/NovelServiceV0.java
- 회원 탈퇴
- 로그 아웃
- 업데이트
- JWT 토큰 값 변경
- Swagger 적용
> 내 정보 기능 구현 완료

- src/main/java/us/usserver/global/config/RedisConfig.java
- src/main/java/us/usserver/global/jwt/TokenProvider.java
> [docs] application-env.yml 값들 서버 내 환경 변수로 이전

- appspec.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정 2

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정 3

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정 4

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정 6

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정 7

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정 8

- appspec.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 명령어 재수정 9

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] application property들 action secrets에서 직접 추가로 변경

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] application property들 action secrets에서 직접 추가로 변경 2

- appspec.yml
- scripts/deploy.sh
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] CD 용 스크립트 작성

- scripts/deploy.sh
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] CD 스크립트 수정

- appspec.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] CD 스크립트 수정 2

- appspec.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] mode 제거

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 스크립트 수정

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 스크립트 수정2

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 스크립트 수정3

- .github/workflows/ci.cd.prod.yml
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [cicd] 컨테이너 인바운드 포트 변경

- Dockerfile
> ...
***
1. ...
2. .......
***
1. ...
2. .......
> [docs] dockerfile jdk 버전 변경

- .github/workflows/ci.cd.prod.yml
> [cicd] Docker 컨테이너 자동 삭제 명령 추가

- src/main/java/us/usserver/author/Author.java
- src/main/java/us/usserver/bookshelf/service/BookshelfServiceV1.java
- src/main/java/us/usserver/comment/CommentController.java
- src/main/java/us/usserver/like/novel/NovelLikeRepository.java
- src/main/java/us/usserver/like/novel/repository/NovelLikeRepositoryImpl.java
- src/main/java/us/usserver/like/novel/service/NovelLikeServiceV0.java
> 회의 후 수정 사항들 반영했습니다.
그리고 종두님이 2024.02.23 부로 미국으로 출발하셔서.
제가 2024.02.14 회의 수정 사항까지 반영해서 다음 PR에 올리겠습니다.
***
1. 댓글 작성 오류 해결
2. 문단 간격 기본 설정 값 변경
3. 보관함 삭제 기능 추가
***
- 보관함 삭제 기능 중, 생성한 소설, 참여한 소설은 구체적인 유저 플로우가 나오기 전까지 보류
> 2024.02.21 회의 후 수정 사항들 반영

- src/main/java/us/usserver/global/filter/JwtAuthenticationFilter.java
> 사용자 토큰이 없어서 http request에서 오류가 발생
***
1. 일단 모든 URL에 대해서 요청을 허용하게 만들었는데 다음 사용자 로그인 리펙토링 때 이 부분까지 같이 해결해야함
> [fix] 사용자 토큰 오류 해결

- .github/workflows/ci.cd.prod.yml
> test runner 배포 테스트 때문에 일단 주석 처리
> [docs] 테스트를 위해 test runner 주석 처리

- .github/workflows/ci.cd.prod.yml
> [docs] 태그 오타 수정

- src/main/java/us/usserver/domain/novel/service/NovelServiceImpl.java
> author가 조회되지 않으면 404 에러를 반환했는데, 소설 메인 페이지는 비회원도 로그인이 가능해야 해서 에러 반환 수정
> [fix] author 조회 오류 수정

- src/main/java/us/usserver/domain/novel/dto/NovelDetailInfo.java
- src/main/java/us/usserver/domain/novel/service/NovelServiceImpl.java
> ...
1. ...
2. .......
1. ...
2. .......
> [fix] 소설 좋아요 유무 나오지 않는 오류 해결

- src/main/java/us/usserver/domain/chapter/dto/ChapterDetailInfo.java
- src/main/java/us/usserver/domain/chapter/service/ChapterServiceImpl.java
- src/main/java/us/usserver/domain/novel/dto/NovelInfo.java
- src/main/java/us/usserver/domain/paragraph/service/ParagraphServiceImpl.java
> ...
1. ...
2. .......
1. ...
2. .......
> 수정 요청 사항 반영
